services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"

  wordpress:
    build:
    image:
    restart: always
    ports:
      - ""
    environment:
      - name=value


