services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - wp-volume:/var/www/html:ro
      - ./requirements/nginx/conf:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    extra_hosts:
      - "andmadri.42.fr:127.0.0.1"

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - wp-volume:/var/www/html:rw
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    extra_hosts:
      - "andmadri.42.fr:127.0.0.1"

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    extra_hosts:
      - "andmadri.42.fr:127.0.0.1"
    
volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wp
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db


networks:
  inception:
    driver: bridge
