services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - /home/andmadri/data/wp:/var/www/html:ro
      - ./requirements/nginx/conf:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - /home/andmadri/data/wp:/var/www/html:rw
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - /home/andmadri/data/db:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "bash", "-c", "mysqladmin ping -hmariadb -u${DB_USR} -p${DB_USR_PWD} 
              && mysql -hmariadb -u${DB_USR} -p${DB_USR_PWD} -e 'SHOW DATABASES;' | grep ${DB_NAME}"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - inception

networks:
  inception:
    driver: bridge
