services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - /home/andmadri/data/wp:/var/www/html:ro
      - ./requirements/nginx/conf:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - /home/andmadri/data/wp:/var/www/html:rw
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - /home/andmadri/data/db:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USR}
      - MYSQL_PASSWORD=${DB_USR_PWD}
      - MYSQL_ROOT_PASSWORD=${DB_USR_PWD}
      - MYSQL_PORT=${DB_PORT}
    healthcheck:
      test: [ "", "" ]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - inception

networks:
  inception:
    driver: bridge
