services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - /home/andmadri/data/wp:/var/www/html:ro
      - ./requirements/nginx/conf:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - /home/andmadri/data/wp:/var/www/html:rw
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - /home/andmadri/data/db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

networks:
  inception:
    driver: bridge
